### ISSUE TITLE
Resize-error in all_overlaps_both

### ISSUE THREAD

**Issue by endrebak** [biocore-ntnu/ncls#41]
https://github.com/biocore-ntnu/pyranges/issues/167

**Comment by jd3builds** [comment]
Any update on this? I'm getting a similar error. I'm using the C/Cython method for deriving the overlaps and getting something like this: 

`Traceback (most recent call last):
  File "C:/Users/PycharmProjects/MobNetMatchingGroup/main.py", line 139, in <module>
    main()
  File "C:/Users/PycharmProjects/MobNetMatchingGroup/main.py", line 130, in main
    l_indices, r_indices = ncl_month.all_overlaps_both(april_2012_dataset.startTime.values, april_2012_dataset.endTime.values, april_2012_dataset.index.values)
  File "ncls/src/ncls.pyx", line 75, in ncls.src.ncls.NCLS64.all_overlaps_both
    cpdef all_overlaps_both(self,
  File "ncls/src/ncls.pyx", line 116, in ncls.src.ncls.NCLS64.all_overlaps_both
    output_arr = np.resize(output_arr, length)
  File "<__array_function__ internals>", line 5, in resize
  File "C:\Users\PycharmProjects\MobNetMatchingGroup\venv\lib\site-packages\numpy\core\fromnumeric.py", line 1425, in resize
    raise ValueError('all elements of `new_shape` must be non-negative')
ValueError: all elements of `new_shape` must be non-negative`

unsure what the fix might be, as this seems to be internal.

**Comment by endrebak** [comment]
I think it is just an overflow error. You have too many hits?
